services:
  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-docker}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS:-mongo}
      MONGO_INITDB_DATABASE: ${MONGO_DATA:-example}
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongo_data:/etc/mongo
volumes:
  mongo_data:
