abbr s 'source'
abbr c 'code'
abbr c. 'code .'
abbr c! 'code -r . && exit'
abbr nv 'nvim'
abbr nv. 'nvim .'
abbr gllg "git log --pretty=format:'%C(yellow)%h %Cred%ad %Cblue<%an>%Creset %s %Cgreen%C(bold)%cr%Creset%C(magenta)%d' --max-count=30 --date=short"
abbr d 'docker'
abbr dc 'docker compose'
abbr dp 'docker pull'
abbr dr 'docker run'
abbr dr 'docker remove'
abbr dri 'docker image remove'
abbr dps 'docker ps'
abbr dpa 'docker ps -a'
abbr dst 'docker start'
abbr dsp 'docker stop'
abbr m 'mise'
abbr f 'fisher'
abbr fu 'fisher update'
abbr fi 'fisher install'
abbr fr 'fisher remove'
abbr fl 'fisher list'

