default_channel = "files"
global_history = false

[ui]
ui_scale = 100
theme = "catppuccin"

[ui.status_bar]
hidden = true

[keybindings]
ctrl-w = "delete_prev_word"
ctrl-d = "delete_line"
ctrl-i = "go_to_input_start"
ctrl-a = "go_to_input_end"

[shell_integration]
fallback_channel = "files"

[shell_integration.keybindings]
"smart_autocomplete" = "ctrl-b"
"command_history" = "ctrl-r"

[shell_integration.channel_triggers]
"env" = ["export", "unset", "set"]
"dirs" = ["cd", "ls", "rmdir"]
"files" = [
  "cat",
  "less",
  "head",
  "tail",
  "vim",
  "nano",
  "bat",
  "cp",
  "mv",
  "rm",
  "touch",
  "chmod",
  "chown",
  "ln",
  "tar",
  "zip",
  "unzip",
  "gzip",
  "gunzip",
  "xz",
]
"git-diff" = ["git add", "git restore"]
"git-branch" = [
  "git checkout",
  "git branch",
  "git merge",
  "git rebase",
  "git pull",
  "git push",
]
"git-log" = ["git log", "git show"]
"git-repos" = ["nvim", "code", "hx", "git clone"]
"docker-images" = ["docker run"]
