add_newline = false
format = """$username[@](bold)$hostname $directory$sudo$character"""
right_format = """
$cmd_duration
$battery
$git_branch
$git_status
$package
$nodejs
$bun
$deno
$java
$php
$python
$dotnet
$rust
$golang
$kotlin
$haskell
$c
$lua
"""

[username]
format = "[$user]($style)"
show_always = true

[hostname]
ssh_only = false
format = "[$hostname$ssh_symbol]($style)"
ssh_symbol = "󰖟"
style = "red bold"

[character]
error_symbol = "[](red bold)"
success_symbol = "[](green bold)"
vimcmd_symbol = "[](green bold)"
vimcmd_replace_one_symbol = "[](purple bold)"
vimcmd_replace_symbol = "[](purple bold)"
vimcmd_visual_symbol = "[](yellow bold)"

[directory]
format = "[$path]($style)"
read_only_style = "cyan"
truncation_length = 1
truncate_to_repo = false

[shell]
disabled = false
style = "black bold"
format = "[ $indicator ]($style)"
fish_indicator = "󰻴"
bash_indicator = ""
nu_indicator = ""
zsh_indicator = ""
cmd_indicator = ""
powershell_indicator = ""

[package]
format = "[ $symbol $version ]($style)"
version_format = "${raw}"
style = "bold dimmed yellow"
symbol = "󰏗"

[nodejs]
format = "[ $symbol $version ]($style)"
version_format = "${raw}"
style = "bold dimmed green"
symbol = ""

[bun]
format = "[ $symbol $version ]($style)"
version_format = "${raw}"
style = "bold dimmed red"
symbol = ""

[deno]
format = "[ $symbol $version ]($style)"
version_format = "${raw}"
style = "bold dimmed cyan"
symbol = ""

[java]
format = "[ $symbol $version ]($style)"
version_format = "${raw}"
style = "bold dimmed red"
symbol = ""

[php]
format = "[ $symbol $version ]($style)"
version_format = "${raw}"
style = "bold dimmed blue"
symbol = ""

[python]
format = "[ $symbol $version ]($style)"
version_format = "${raw}"
style = "bold dimmed blue"
symbol = ""

[dotnet]
format = "[ $symbol $version ]($style)"
version_format = "${raw}"
style = "bold dimmed purple"
symbol = ""

[rust]
format = "[ $symbol $version ]($style)"
version_format = "${raw}"
style = "bold dimmed yellow"
symbol = ""

[golang]
format = "[ $symbol $version ]($style)"
version_format = "${raw}"
style = "bold dimmed cyan"
symbol = ""

[kotlin]
format = "[ $symbol $version ]($style)"
version_format = "${raw}"
style = "bold dimmed blue"
symbol = ""

[haskell]
format = "[ $symbol $version ]($style)"
version_format = "${raw}"
style = "bold dimmed purple"
symbol = ""

[c]
format = "[ $symbol $version ]($style)"
version_format = "${raw}"
style = "bold dimme purple"
symbol = ""

[lua]
format = "[ $symbol $version ]($style)"
version_format = "${raw}"
style = "bold dimmed blue"
symbol = "󰢱"

[git_branch]
format = "[ $symbol $branch ]($style)"
style = "bold dimmed purple"
symbol = ""

[git_status]
style = "bold dimmed italic purple"

[time]
disabled = false
style = "black bold"
format = "[ $time ]($style)"

[cmd_duration]
disabled = false
style = "black bold"
format = "[ took $duration ]($style)"

[battery]
display = [{ style = "black bold", threshold = 80 }]
format = "[ $symbol$percentage ]($style)"

[sudo]
disabled = false
style = "bold black"
format = "[$symbol]($style)"
symbol = " sudo "
