format = "$all"
right_format = " $sudo$memory_usage$battery$time$shell$os "
add_newline = false

[username]
style_user = "bold red"
style_root = "bg:red fg:black"
format = "[$user]($style) in "
disabled = false
show_always = true

[character]
format = "$symbol  "
error_symbol = '[](red)'
success_symbol = '[](green)'
vimcmd_symbol = '[](green)'
vimcmd_replace_one_symbol = '[](purple)'
vimcmd_replace_symbol = '[](purple)'
vimcmd_visual_symbol = '[](yellow)'

[directory]
format = "[$read_only]($read_only_style)[$path]($style) "
read_only = " "
home_symbol = " "
read_only_style = "cyan"
truncation_length = 1
style = "italic bold cyan"

[directory.substitutions]
"Annotations" = " "
"Notes" = " "
"Documents" = "󰈙 "
"Documentos" = "󰈙 "
"Modelos" = "󰛼 "
"Models" = "󰛼 "
"Downloads" = " "
"Music" = "󰝚 "
"Músicas" = "󰝚 "
"Pictures" = " "
"Imagens" = " "
"Developer" = "󰲋 "
"Dev" = "󰲋 "
"Projects" = "󰲋 "
"Games" = "󰮂 "
"Público" = "󰖟 "
"Public" = "󰖟 "
"Vídeos" = " "
"Desktop" = " "
"Área de trabalho" = " "
"Dotfiles" = " "
"Config" = " "
"Configurations" = " "

[shell]
disabled = false
style = "black bold"
format = "[ $indicator ]($style)"
fish_indicator = "󰻴"
bash_indicator = ""
nu_indicator = ""
zsh_indicator = ""
cmd_indicator = ""
powershell_indicator = ""

[package]
format = 'is[ $symbol $version ]($style)'
version_format = "${raw}"
style = "bold yellow"
symbol = "󰏗"

[nodejs]
format = 'via[ $symbol $version ]($style)'
version_format = "${raw}"
style = "bold green"
symbol = ""

[bun]
format = 'via[ $symbol $version ]($style)'
version_format = "${raw}"
style = 'bold red'
symbol = ''

[deno]
format = 'via[ $symbol $version ]($style)'
version_format = "${raw}"
style = "bold cyan"
symbol = ""

[java]
format = 'via[ $symbol $version ]($style)'
version_format = "${raw}"
style = "bold red"
symbol = ""

[php]
format = 'via[ $symbol $version ]($style)'
version_format = "${raw}"
style = "bold blue"
symbol = ""

[python]
format = 'via[ $symbol $version ]($style)'
version_format = "${raw}"
style = 'bold blue'
symbol = ""

[dotnet]
format = 'via[ $symbol $version ]($style)'
version_format = "${raw}"
style = "bold purple"
symbol = ""

[rust]
format = 'via[ $symbol $version ]($style)'
version_format = "${raw}"
style = "bold yellow"
symbol = ""

[golang]
format = 'via[ $symbol $version ]($style)'
version_format = "${raw}"
style = "bold cyan"
symbol = ""

[kotlin]
format = 'via[ $symbol $version ]($style)'
version_format = "${raw}"
style = "bold blue"
symbol = ""

[haskell]
format = 'via[ $symbol $version ]($style)'
version_format = "${raw}"
style = "bold purple"
symbol = ""

[c]
format = 'via[ $symbol $version ]($style)'
version_format = "${raw}"
style = "bold purple"
symbol = ""

[lua]
format = 'via[ $symbol $version ]($style)'
version_format = "${raw}"
style = "bold blue"
symbol = "󰢱"

[git_branch]
symbol = ""
style = "bold purple"
format = "on[ $symbol $branch ]($style)"

[git_status]
style = "bold italic purple"

[git_state]
format = '[\($state( $progress_current/$progress_total)\) ]($style)'
style = "bold italic dimmed purple"

[time]
disabled = true
time_format = "%R"
style = "black bold"
format = "[ $time ]($style)"

[cmd_duration]
disabled = false
style = "black bold"
format = "[took $duration]($style)"

[os]
disabled = false
style = "black bold"
format = "[ $symbol ]($style)"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = ""
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[battery]
display = [{ style = "black bold", threshold = 60 }]
format = "[ $symbol$percentage ]($style)"

[sudo]
disabled = false
style = "bold black"
format = "[ $symbol ]($style)"
symbol = "sudo"

[memory_usage]
disabled = false
format = "[ ${ram} | ${swap} ]($style)"
threshold = 75
style = "bold black"
symbol = "󰍛"
