_G.icons = {
  database = " ",
  terminal = " ",
  rocket = " ",
  exit = " ",
  file = " ",
  files = " ",
  flame = " ",
  keyboard = " ",
  play = " ",
  source = " ",
  git = {
    branch = " ",
    status = {
      added = " ",
      modified = " ",
      removed = " ",
    },
  },
  lsp = {
    error = " ",
    hint = " ",
    info = " ",
    warn = " ",
  },
  package = {
    i = " ",
    installed = " ",
    uninstalled = " ",
    pending = " ",
    dependencies = " ",
    depends = " ",
    enabled = " ",
    disabled = " ",
  },
  search = " ",
  server = " ",
  text = " ",
  tool = " ",
}
