#! /usr/bin/env fish

if not set -q TMUX
    echo "not in a tmux session"
    exit 1
end

set sessions
set current_tmux_session (tmux display-message -p '#S')
set tmux_sessions (tmux ls -F '#S')
set dir_sessions (printf '%s\n' (ls ~/Projects/; ls ~) | sort)

for session in $tmux_sessions
    if test "$session" != "$current_tmux_session"
        set sessions $sessions "$session *"
    end
end

for dir in $dir_sessions
    if not contains $dir $tmux_sessions
        set sessions $sessions $dir
    end
end

set selected (
    printf '%s\n' $sessions | fzf \
        --input-label "" \
        --bind 'enter:become(echo {1})' \
        --no-sort \
        --border-label ' Let-Sessions ' \
        --preview-label ' Preview (ls output) ' \
        --preview 'fish -c "
            if test {1} = \"Default\";
              eza --color always $HOME;
            else;
              eza --color always (fd {1} $HOME -1 -d 2 -t d);
            end;
        " ' \
        --ghost ' Search for a session' \
        --list-label ' Sessions ' \
        --tmux 60% || true
)

test -z "$selected"; and return

if not tmux has-session -t $selected 2>/dev/null
    tmux new-session -d -s $selected -c (fd $selected ~ -1)
end

tmux switch-client -t $selected
