git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  parseEmoji: true

gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - cyan
    selectedLineBgColor:
      - black

  branchColorPatterns:
    "^(main|master|dev|develop|development|stage)$": magenta
    "^(docs|documentation)/": blue
    "^(feat|feature)/": yellow
    "^(refc|refac|refactor|refactoring)/": green
    "^(bug|bugfix|hotfix|fix)/": red
    "^(test|testing)/": cyan
    "^(chore)/": white

  authorColors:
    "*": cyan
    "Rafael Scalet": magenta
    "Murilo Santos": blue
    "Angelo Ferraz Modanez": yellow
