git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
    useConfig: false

gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - cyan
    selectedLineBgColor:
      - black

  branchColorPatterns:
    '^(main|master|dev|develop|development)$': magenta
    '^(docs|documentation)$/': blue
    '^(feat|feature)$/': yellow
    '^(refc|refac|refactor|refactoring)$/': green
    '^(bug|bugfix|hotfyx)$/': red
    '^(test|testing)$/': cyan
    '^(chore)$/': black

  authorColors:
    '*': cyan
    'Rafael Scalet': magenta
    'Murilo Santos': blue
    'Angelo Ferraz Modanez': yellow
