complete -f -c fundle -a init -d "load all plugins"
complete -f -c fundle -a plugin -d "add a plugin"
complete -f -c fundle -a list -d "list plugins"
complete -f -c fundle -a install -d "install all plugins"
complete -f -c fundle -a update -d "update existing plugins"
complete -f -c fundle -a clean -d "cleans unused plugins"
complete -f -c fundle -a self-update -d "update fundle"
complete -f -c fundle -a version -d "display fundle version"
complete -f -c fundle -a help -d "display helps"
