services:
  grafana:
    image: docker.io/grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    network_mode: bridge
volumes:
  grafana_data:
