return {
  database = " ",
  terminal = " ",
  rocket = " ",
  exit = " ",
  flame = " ",
  fs = {
    file = {
      i = " ",
      add = " ",
      two = " ",
      readonly = " ",
      modified = " ",
    },
    folder = {
      fill = {
        closed = " ",
        opened = " ",
      },
      closed = " ",
      opened = " ",
    },
  },
  listchars = {
    space = "·",
    tab = "» ",
    trail = "•",
    extends = "⟩",
    precedes = "⟨",
    eol = "↲",
    nbsp = "␣",
  },
  fillchars = {
    eob = "~",
    fold = " ",
    foldsep = " ",
    foldopen = "",
    foldclose = "",
  },
  keyboard = " ",
  play = " ",
  source = " ",
  git = {
    i = "󰊢 ",
    branch = " ",
    status = {
      added = " ",
      modified = " ",
      removed = " ",
    },
  },
  lsp = {
    i = " ",
    kind = {
      File = " ",
      Module = " ",
      Struct = " ",
      Package = " ",
      Method = " ",
      Namespace = " ",
      Class = " ",
      Property = " ",
      Field = " ",
      Enum = " ",
      EnumMember = " ",
      Variable = " ",
      Constant = " ",
      String = " ",
      Text = " ",
      Key = " ",
      Keyword = " ",
      Constructor = " ",
      Snippet = " ",
      Interface = " ",
      Function = " ",
      Number = " ",
      Boolean = " ",
      Array = " ",
      Object = " ",
      Null = " ",
      Event = " ",
      Operator = " ",
      TypeParameter = " ",
    },
    diagnostics = {
      error = " ",
      hint = " ",
      info = " ",
      warn = " ",
    },
  },
  package = {
    i = " ",
    installed = " ",
    uninstalled = " ",
    pending = " ",
    dependencies = " ",
    depends = " ",
    enabled = " ",
    disabled = " ",
  },
  toggle = " ",
  search = " ",
  server = " ",
  text = " ",
  key = " ",
  tag = " ",
  tool = " ",
}
