unbind r
bind r source-file ~/.config/tmux/tmux.conf

set -g prefix C-a
unbind C-b
bind C-a send-prefix

bind | split-window -h -c "#{pane_current_path}"
bind \\ split-window -h -c "#{pane_current_path}"

bind - split-window -v -c "#{pane_current_path}"

unbind f
bind f new-window -c "#{pane_current_path}" "fish"

unbind n
bind n new-window -c "#{pane_current_path}" "nu"

unbind b
bind b new-window -c "#{pane_current_path}" "bash"

bind ";" command-prompt

bind -n M-H previous-window
bind -n M-L next-window

set -g base-index 1
set -g renumber-windows on

set-option -g status-position top

set -g mouse on
set -g xterm-keys on
set -g mode-keys vi

# Catppuccin configuration
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_current_number_color "#{@thm_mauve}"
set -g @catppuccin_window_number_color "#{@thm_lavender}"
set -g @catppuccin_window_text " #{pane_current_command}"
set -g @catppuccin_window_current_text " #{pane_current_command} *"

set -g status-left ""
set -g status-right "#{E:@catppuccin_status_date_time}#{E:@catppuccin_status_session}"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'TheSast/tmux-nav-master'
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'alexwforsythe/tmux-which-key'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-ressurect'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

set -g status-style bg=default
