# Options
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

set-option -g detach-on-destroy off
set-option -g exit-empty off

set -g mouse on

set -g prefix C-a

# Bindings
bind \\ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

bind e new-window -c "#{pane_current_path}" "exec nvim"
bind g new-window -c "#{pane_current_path}" "exec lazygit"
bind d new-window -c "#{pane_current_path}" "exec lazydocker"
bind b new-window -c "#{pane_current_path}" "exec btm"
bind c new-window -c "#{pane_current_path}" "exec fish"
bind u new-window -c "#{pane_current_path}" "exec gdu"

bind X kill-session

bind A copy-mode
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Tmux Plugin Manager Installation
if-shell '[ -z "$XDG_DATA_HOME" ]' {
  XDG_DATA_HOME="$HOME/.local/share"
  display-message "WARNING: XDG_DATA_HOME is not set, falling back to $HOME/.local/share/"
}

set-environment -g -F TMUX_PLUGIN_MANAGER_PATH "${XDG_DATA_HOME}/tmux/plugins"

if-shell '[ ! -d "${TMUX_PLUGIN_MANAGER_PATH}/tpm" ]' {
  run-shell 'git clone https://github.com/tmux-plugins/tpm ${TMUX_PLUGIN_MANAGER_PATH}/tpm'
  run-shell '${TMUX_PLUGIN_MANAGER_PATH}/tpm/bin/install_plugins'
}

# My custom status bar inspired by catppuccin
if-shell '[ -z "$XDG_CONFIG_HOME" ]' {
  XDG_CONFIG_HOME="$HOME/.config"
  display-message "WARNING: XDG_CONFIG_HOME is not set, falling back to $HOME/.config"
}

source "${XDG_CONFIG_HOME}/tmux/status.tmux"

# Plugins Configs
set -g @sessionx-bind 'o'
set -g @sessionx-window-height '90%'
set -g @sessionx-x-path '$HOME/Projects/'
set -g @sessionx-ls-command 'eza --icons --oneline --color=always --group-directories-first --no-quotes'

# Plugins Definitions
set -g @plugin 'alexwforsythe/tmux-which-key'
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'rafascalet/tmux-nav-master'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tpm'

# Plugins "Source"
run-shell "#{TMUX_PLUGIN_MANAGER_PATH}/tpm/tpm"
