# Options
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

set -g popup-border-lines rounded
set -g popup-border-style "bg=default,fg=blue"

set -g detach-on-destroy off
set -g exit-empty off

set -g default-shell /usr/bin/fish
set -g default-command /usr/bin/fish

set -g mouse on

set -g prefix C-a

# Bindings
bind -N "Split window horizontally" \\ split-window -h -c "#{pane_current_path}"
bind -N "Split window vertically" - split-window -v -c "#{pane_current_path}"

bind -N "New Window" c new-window -c "#{pane_current_path}" "exec $SHELL"
bind -N "$EDITOR" e new-window -a -c "#{pane_current_path}" "exec $EDITOR"
bind -N "lazygit" g new-window -a -c "#{pane_current_path}" "exec lazygit"
bind -N "lazydocker" d new-window -a -c "#{pane_current_path}" "exec lazydocker"
bind -N "compose files" D new-window -a -c "~/Dotfiles/docker/compose/" "exec lazydocker"
bind -N "bottom" b new-window -a -c "#{pane_current_path}" "exec btm"

bind -N "Topgrade" C-u run-shell "topgrade"

bind -N "kill current window" X confirm-before -p "kill-window #W? (y/n)" kill-window
bind -N "Kill attached session" C-x confirm-before -p "kill-session #S? (y/n)" kill-session

bind -N "Session/Project Manager" o run-shell "tmux-fzf-sessions"
bind -N "Search for a man page" C-m run-shell "tmux-fzf-man-pages"

bind -N "Enter tmux copy mode" -n "C-;" copy-mode
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Tmux Plugin Manager Installation
if-shell '[ -z "$XDG_DATA_HOME" ]' {
  XDG_DATA_HOME="$HOME/.local/share"
  display-message "WARNING: XDG_DATA_HOME is not set, falling back to $HOME/.local/share/"
}

set-environment -g -F TMUX_PLUGIN_MANAGER_PATH "${XDG_DATA_HOME}/tmux/plugins"

if-shell '[ ! -d "${TMUX_PLUGIN_MANAGER_PATH}/tpm" ]' {
  run-shell 'git clone https://github.com/tmux-plugins/tpm ${TMUX_PLUGIN_MANAGER_PATH}/tpm'
  run-shell '${TMUX_PLUGIN_MANAGER_PATH}/tpm/bin/install_plugins'
}

# My custom status bar inspired by catppuccin
if-shell '[ -z "$XDG_CONFIG_HOME" ]' {
  XDG_CONFIG_HOME="$HOME/.config"
  display-message "WARNING: XDG_CONFIG_HOME is not set, falling back to $HOME/.config"
}

source "${XDG_CONFIG_HOME}/tmux/status.tmux"

# Plugins Definitions
set -g @plugin 'wfxr/tmux-fzf-url'
set -g @plugin 'rafascalet/tmux-nav-master'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tpm'

# Plugins "Source"
run-shell "#{TMUX_PLUGIN_MANAGER_PATH}/tpm/tpm"
